### ISSUE TITLE
Dataset ending in .exe

### ISSUE THREAD

**Issue by madalincostea** [AndreGuo/HDRTVDM#2]
May I ask why are the datasets available for download ending in .exe? This does not seem safe.

Also the link for - HDRTV4K label HDR is not working.

**Comment by zzk-000** [comment]
感谢您的开源分享，不过我在下载数据集的时候遇到两个问题：
1. HDRTV4K label HDR的链接不存在；
2. 2446c+GM的AliyunDrive链接内容是sdr_ocio2.exe；

**Comment by AndreGuo** [comment]
It's now released, please check.
We provide .exe in AliyunDrive since it donnot support sharing .zip, .exe there is a self-extract file and you can run it at WIndow system.
阿里云盘不支持分享.zip，所以我们上传了.exe的自解压文件，您可以在window上运行它。
