### ISSUE TITLE
About the metric proposed in paper

### ISSUE THREAD

**Issue by syujung** [AndreGuo/HDRTVDM#3]
Dear author,
    Thanks for your great work! I have some issues about the metric (FHLP,EHL,FWGP,EWG,….)proposed in paper, could you release the related code of these metrics?  
    Looking forward to your reply!

**Comment by AndreGuo** [comment]
It's now released, plz check.

**Comment by jchhuang** [comment]
Dear author, a total of 7 metrics are mentioned on your paper, however only 4 implementation of them are posted on this repo, may you share the code of other 3 metrics
